name: CD (Deploy to Azure)

on:
  push:
    branches: ["main", "release"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            export DOCKER_BUILDKIT=1
            export COMPOSE_DOCKER_CLI_BUILD=1

            BRANCH="${{ github.ref_name }}"

            if [ ! -d "my-app" ]; then
              git clone -b $BRANCH https://github.com/A7reus/ci-cd-test.git my-app
            fi
            cd my-app
            git fetch origin $BRANCH
            git switch $BRANCH
            git pull origin $BRANCH

            # Dynamically create the .env file from GitHub Secrets
            cat <<EOF > .env
            POSTGRES_DB_NAME=${{ secrets.POSTGRES_DB_NAME }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWD=${{ secrets.POSTGRES_PASSWD }}
            POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
            EOF

            docker-compose down --remove-orphans || true
            docker-compose up -d --build --force-recreate
            docker image prune -f
